---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: skipverify
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: kanidm
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: {{ .Release.Namespace }}-skipverify@kubernetescrd
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: ldaps
    port: 636
    targetPort: 3636
    protocol: TCP
  selector:
    app: kanidm
