host: insidan.linkopingsfallskarmsklubb.local
tls: false

server:
  cookieDomain: "linkopingsfallskarmsklubb.local"

oauth2:
  clientId: insidan
  clientSecretRef: authelia-client-insidan-secret
  authUrl: http://auth.linkopingsfallskarmsklubb.local/api/oidc/authorization
  tokenUrl: http://auth.linkopingsfallskarmsklubb.local/api/oidc/token
  redirectUrl: http://insidan.linkopingsfallskarmsklubb.local/api/auth/callback
  defaultRedirect: http://insidan.linkopingsfallskarmsklubb.local/
  scopes: "[openid,profile,email,groups]"

lldap:
  default_groups: "[users, skywin_users]"

skywin:
  url: http://skywinone:8080/skywinone

skywinDb:
  uriRef: insidandev-mysql-uri

swish:
  base_url: "https://mss.cpc.getswish.net/swish-cpcapi/api/v2"
  payeealias: swish-number
  callbackUrlBase: "https://insidan.linkopingsfallskarmsklubb.se/test"
  adminEmail: "ordforande@linkopingsfallskarmsklubb.se"
  paymentFee: 3.0
  clientCertRef: dev-swish-client-cert
  clientKeyRef: dev-swish-client-key
  caCertRef: dev-swish-ca-cert
  clientKeyPasswordRef: dev-swish-client-key-password
  callbackSecretRef: dev-swish-callback-secret
