host: insidan.linkopingsfallskarmsklubb.localhost

server:
  cookieDomain: "linkopingsfallskarmsklubb.localhost"
  logLevel: debug

oauth2:
  clientId: insidan
  clientSecretRef: authelia-client-insidan-secret
  authUrl: https://auth.linkopingsfallskarmsklubb.localhost/api/oidc/authorization
  tokenUrl: https://auth.linkopingsfallskarmsklubb.localhost/api/oidc/token
  redirectUrl: https://insidan.linkopingsfallskarmsklubb.localhost/api/auth/callback
  defaultRedirect: https://insidan.linkopingsfallskarmsklubb.localhost/
  scopes:
    - openid
    - profile
    - email
    - groups

authelia:
  url: https://auth.linkopingsfallskarmsklubb.localhost

hostAliases:
  - ip: "0.0.0.0" # Overridden by global.traefikIp in development
    hostnames:
      - "auth.linkopingsfallskarmsklubb.localhost"
      - "insidan.linkopingsfallskarmsklubb.localhost"

caSecret: mkcert-ca-cert

lldap:
  defaultGroups:
    - users
    - skywin_users

skywin:
  url: http://skywinone:8080/skywinone

skywinDb:
  uriRef: insidandev-mysql-uri

swish:
  base_url: "https://mss.cpc.getswish.net/swish-cpcapi/api/v2"
  payeealias: swish-number
  callbackUrlBase: "https://insidan.linkopingsfallskarmsklubb.localhost/test"
  adminEmail: "ordforande@linkopingsfallskarmsklubb.se"
  paymentFee: 3.0
  clientCertRef: dev-swish-client-cert
  clientKeyRef: dev-swish-client-key
  caCertRef: dev-swish-ca-cert
  clientKeyPasswordRef: dev-swish-client-key-password
  callbackSecretRef: dev-swish-callback-secret
certResolver: ""
