image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/dbtools
  tag: "1.1.1"
  pullPolicy: IfNotPresent

postgres:
  enabled: true
  databases:
    - name: shared
      user: shared
      passwordKey: password
    - name: authelia
      user: authelia
      passwordKey: authelia-password
    - name: lldap
      user: lldap
      passwordKey: lldap-password

mysql:
  enabled: true

skywinBackup:
  location: gs://lfk-backup-prod/skywin

pgBackup:
  location: gs://lfk-backup-prod/postgres
