apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/linkopingsfallskarmsklubb/infrastructure
    path: charts/mysql
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      selfHeal: true
