apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    {{- if ne .Values.tls false }}
    address: http://authelia.{{ .Release.Namespace }}.svc.cluster.local/api/authz/forward-auth?authelia_url=https://auth.linkopingsfallskarmsklubb.se/
    {{- else }}
    address: http://authelia.{{ .Release.Namespace }}.svc.cluster.local/api/authz/forward-auth?authelia_url=http://auth.linkopingsfallskarmsklubb.local/
    {{- end }}
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
