apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: "postgres:{{ .Chart.AppVersion }}"
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: password
            - name: POSTGRES_USER
              value: {{ .Values.user }}
            - name: POSTGRES_DB
              value: {{ .Values.database }}
          volumeMounts:
            - name: postgres-pv-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
