apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        pluginSecret: "{{"{{"}} .plugin_secret | trim {{"}}"}}"
        providerClientSecret: "{{"{{"}} .provider_client_secret | trim {{"}}"}}"
  data:
    - secretKey: plugin_secret
      remoteRef:
        key: {{ .Values.pluginSecretRef }}
    - secretKey: provider_client_secret
      remoteRef:
        key: {{ .Values.providerClientSecretRef }}
