apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: pluginSecret
      remoteRef:
        key: {{ .Values.pluginSecretRef }}
    - secretKey: providerClientSecret
      remoteRef:
        key: {{ .Values.providerClientSecretRef }}
