apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: default
      traefik.ingress.kubernetes.io/router.middlewares: core-middlewares-authentik@kubernetescrd
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: "/skywinone"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
  tls:
    - hosts:
      - {{ .Values.host }}
