host: insidan.linkopingsfallskarmsklubb.se
# localHost: 192.168.30.114
localHost: 10.96.32.102
secretStore: secret-store
providerUrl: https://auth.linkopingsfallskarmsklubb.se
clientId: skywinone
pluginSecretRef: skywinone-plugin-secret
providerClientSecretRef: authelia-client-skywinone-secret
certResolver: default
