authentik:
  server:
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: default
      hosts:
        - insidan.linkopingsfallskarmsklubb.se
