replicaCount: 1

image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/skywinone
  tag: "26.0.4.0.2.0"
  pullPolicy: IfNotPresent

secretStore: secret-store
skywinonePropertiesRef: skywinone-properties

host: ""
tls: false