{{- if not .Values.proxy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if or .Values.hostAliases .Values.global }}
      hostAliases:
        {{- if and .Values.global .Values.global.traefikIp }}
        - ip: {{ .Values.global.traefikIp | quote }}
          hostnames:
            {{- range .Values.hostAliases }}
            {{- toYaml .hostnames | nindent 12 }}
            {{- end }}
        {{- else }}
        {{- toYaml .Values.hostAliases | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_OAUTH2__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: insidan-client-secret
            - name: API_LLDAP__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: lldap-password
            - name: API_SKYWIN__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: skywin-password
            - name: API_SKYWIN_DB__URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: skywin-db-uri
            - name: API_COMMON_DB__URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: common-db-uri
            - name: API_SWISH__PAYEE_ALIAS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: swish-payee-alias
            - name: API_SWISH__CLIENT_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: swish-client-key-password
            - name: API_SWISH__CALLBACK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: swish-callback-secret
            - name: API_WIX__API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: wix-api-key
            - name: API_WIX__SITE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: wix-site-id
            - name: API_WIX__ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: wix-account-id
            {{- if .Values.caSecret }}
            - name: API_EXTRA_CA_CERT
              value: "/etc/ssl/certs/ca.crt"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: swish-certs
              mountPath: /etc/swish
              readOnly: true
            {{- if .Values.caSecret }}
            - name: ca-cert
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
              readOnly: true
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
        - name: swish-certs
          secret:
            secretName: {{ .Release.Name }}
            items:
              - key: swish-client-cert
                path: client-cert.pem
              - key: swish-client-key
                path: client-key.pem
              - key: swish-ca-cert
                path: ca-cert.pem
        {{- if .Values.caSecret }}
        - name: ca-cert
          secret:
            secretName: {{ .Values.caSecret }}
        {{- end }}
{{- end }}
