apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  data:
    - secretKey: insidan-client-secret
      remoteRef:
        key: {{ .Values.oauth2.clientSecretRef }}
    - secretKey: lldap-password
      remoteRef:
        key: {{ .Values.lldap.passwordRef }}
    - secretKey: skywin-password
      remoteRef:
        key: {{ .Values.skywin.passwordRef }}
    - secretKey: skywin-db-uri
      remoteRef:
        key: {{ .Values.skywinDb.uriRef }}
    - secretKey: common-db-uri
      remoteRef:
        key: {{ .Values.commonDb.uriRef }}
    - secretKey: swish-payee-alias
      remoteRef:
        key: {{ .Values.swish.payeealias }}
    - secretKey: swish-client-key-password
      remoteRef:
        key: {{ .Values.swish.clientKeyPasswordRef }}
    - secretKey: swish-client-cert
      remoteRef:
        key: {{ .Values.swish.clientCertRef }}
    - secretKey: swish-client-key
      remoteRef:
        key: {{ .Values.swish.clientKeyRef }}
    - secretKey: swish-ca-cert
      remoteRef:
        key: {{ .Values.swish.caCertRef }}
    - secretKey: swish-callback-secret
      remoteRef:
        key: {{ .Values.swish.callbackSecretRef }}
