argo-cd:
  createAggregateRoles: false
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

ingress:
  enabled: false

secretStore: secret-store
clientSecretRef: argocd-client-secret
