argo-cd:
  createAggregateRoles: false
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure

ingress:
  enabled: false
