argo-cd:
  createAggregateRoles: false
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  configs:
    params:
      server.rootpath: "/argocd"
      server.insecure: true

ingress:
  enabled: false
