authentik:
  authentik:
    secret_key: file:///authentik-secrets/secret-key
    postgresql:
      host: postgres
      user: authentik
      password: file:///authentik-secrets/password

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - ""
    volumes:
      - name: authentik-secrets
        secret:
          secretName: authentik-secrets
    volumeMounts:
      - name: authentik-secrets
        mountPath: /authentik-secrets
        readOnly: true

  worker:
    volumes:
      - name: authentik-secrets
        secret:
          secretName: authentik-secrets
    volumeMounts:
      - name: authentik-secrets
        mountPath: /authentik-secrets
        readOnly: true

  redis:
    enabled: true

secretStore: secret-store
postgresPasswordRef: authentik-postgres-password
secretKeyRef: authentik-secret-key
