authentik:
  global:
    env:
      - name: AUTHENTIK_BOOTSTRAP_EMAIL
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: bootstrap-email
      - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: bootstrap-password
      - name: AUTHENTIK_BOOTSTRAP_TOKEN
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: bootstrap-token

  authentik:
    secret_key: file:///authentik-secrets/secret-key
    web:
      path: /authentik/
    postgresql:
      host: postgres
      user: authentik
      password: file:///authentik-secrets/password

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - "localhost"
    volumes:
      - name: authentik-secrets
        secret:
          secretName: authentik-secrets
    volumeMounts:
      - name: authentik-secrets
        mountPath: /authentik-secrets
        readOnly: true

  worker:
    volumes:
      - name: authentik-secrets
        secret:
          secretName: authentik-secrets
    volumeMounts:
      - name: authentik-secrets
        mountPath: /authentik-secrets
        readOnly: true

  redis:
    enabled: true

secretStore: secret-store
postgresPasswordRef: authentik-postgres-password
secretKeyRef: authentik-secret-key
bootstrapEmailRef: authentik-bootstrap-email
bootstrapPasswordRef: authentik-bootstrap-password
bootstrapTokenRef: authentik-bootstrap-token
