apiVersion: apps/v1
kind: Deployment
metadata:
  name: ellen
  labels:
    app: ellen
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ellen
  template:
    metadata:
      labels:
        app: ellen
    spec:
      {{- if or .Values.hostAliases .Values.global }}
      hostAliases:
        {{- if and .Values.global .Values.global.traefikIp }}
        - ip: {{ .Values.global.traefikIp | quote }}
          hostnames:
            {{- range .Values.hostAliases }}
            {{- toYaml .hostnames | nindent 12 }}
            {{- end }}
        {{- else }}
        {{- toYaml .Values.hostAliases | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: ellen
          image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INSIDAN_API_URL
              value: "{{ .Values.insidanApiUrl }}"
            - name: INSIDAN_TOKEN_URL
              value: "{{ .Values.insidanTokenUrl }}"
            - name: INSIDAN_CLIENT_ID
              value: "{{ .Values.insidanClientId }}"
            - name: INSIDAN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: client-secret
            - name: GOOGLE_SPREADSHEET_ID
              value: "{{ .Values.googleSpreadsheetId }}"
            - name: GOOGLE_SHEET_TAB
              value: "{{ .Values.googleSheetTab }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/credentials/service-account.json
            - name: POLL_INTERVAL
              value: "{{ .Values.pollInterval }}"
            {{- if .Values.caSecret }}
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/ca.crt
            {{- end }}
          volumeMounts:
            - mountPath: /etc/credentials
              name: google-service-account
              readOnly: true
            {{- if .Values.caSecret }}
            - name: ca-cert
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
              readOnly: true
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: google-service-account
          secret:
            secretName: {{ .Release.Name }}
            items:
              - key: google-service-account
                path: service-account.json
        {{- if .Values.caSecret }}
        - name: ca-cert
          secret:
            secretName: {{ .Values.caSecret }}
        {{- end }}
