host: insidan.linkopingsfallskarmsklubb.se
replicaCount: 1
image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/insidanweb
  tag: "2.2.0"
  pullPolicy: Always
certResolver: default
