domain: idm.linkopingsfallskarmsklubb.se

replicas: 1

storageClassName: "local-path-persistent"

# May be one of info, debug, trace. This may be changed at runtime.
logLevel: "info"

ingress:
  className: traefik
  tlsSecretName: kanidm-tls
