insidanApiUrl: https://insidan.linkopingsfallskarmsklubb.localhost/api
insidanTokenUrl: https://auth.linkopingsfallskarmsklubb.localhost/api/oidc/token

googleSpreadsheetId: "1PpGupmBQzXjDVjLq6egY8UB-vGTy5uJDSbkKzFztB4g" # Ellen - Test

hostAliases:
  - ip: "0.0.0.0"
    hostnames:
      - "auth.linkopingsfallskarmsklubb.localhost"
      - "insidan.linkopingsfallskarmsklubb.localhost"

caSecret: mkcert-ca-cert
