apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: {{ .Values.userPasswordRef }}
    - secretKey: root
      remoteRef:
        key: {{ .Values.rootPasswordRef }}
