
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: skywin
      remoteRef:
        key: mysql-skywin-password
    - secretKey: root
      remoteRef:
        key: mysql-root-password
