apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: "mysql:{{ .Chart.AppVersion }}"
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: root
          volumeMounts:
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql
            - name: mysql-cnf
              mountPath: /etc/mysql/conf.d/
      volumes:
        - name: mysql-cnf
          configMap: 
            name: {{ .Release.Name }}
            items:
              - key: mysql.cnf
                path: mysql.cnf
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv-storage
      spec:
        storageClassName: {{ .Values.storageClass }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.size | default "8Gi" }}
