authelia:
  tls: false
  configMap:
    theme: oled
    session:
      remember_me: "7 days"
      cookies:
        - domain: "linkopingsfallskarmsklubb.local"
          authelia_url: "http://auth.linkopingsfallskarmsklubb.local"
          insecure: true
    identity_providers:
      oidc:
        clients:
          - client_id: "insidan"
            client_name: "Insidan"
            consent_mode: "implicit"
            pre_configured_consent_duration: "1y"
            client_secret:
              path: "/secrets/authelia-secrets/client-insidan-secret"
            public: false
            authorization_policy: "one_factor"
            redirect_uris:
              - "http://localhost:3000/api/auth/callback"
              - "http://localhost:8000/api/auth/callback"
              - "http://insidan.linkopingsfallskarmsklubb.local/api/auth/callback"
            scopes: ["openid", "profile", "email", "groups"]
            grant_types: ["authorization_code"]
    access_control:
      rules:
        - domain: "*.linkopingsfallskarmsklubb.local"
          policy: "one_factor"

  ingress:
    enabled: true
    traefikCRD:
      enabled: true
      disableIngressRoute: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.tls.certresolver: !!null
    rulesOverride:
      - host: auth.linkopingsfallskarmsklubb.local
        path: /
    tls:
      enabled: false
