authelia:
  configMap:
    theme: oled
    session:
      remember_me: "7 days"
      cookies:
        - domain: "127.0.0.1"
    identity_providers:
      oidc:
        clients:
          - client_id: "insidan"
            client_name: "Insidan"
            consent_mode: "implicit"
            pre_configured_consent_duration: "1y"
            client_secret:
              path: "/secrets/authelia-secrets/client-insidan-secret"
            public: false
            authorization_policy: "one_factor"
            redirect_uris:
              - "http://localhost:3000/api/auth/callback"
              - "http://localhost:8000/api/auth/callback"
              - "https://insidan.linkopingsfallskarmsklubb.se/api/auth/callback"
            scopes: ["openid", "profile", "email", "groups"]
            grant_types: ["authorization_code"]
          - client_id: "adsb-state-events"
            client_name: "ADSB State Events"
            client_secret:
              path: "/secrets/authelia-secrets/client-adsb-state-events-secret"
            public: false
            authorization_policy: "one_factor"
            claims_policy: "adsb_state_events_claims"
            scopes: ["profile", "email", "groups"]
            grant_types: ["client_credentials"]
    access_control:
      rules:
        - domain: "127.0.0.1"
          policy: "one_factor"

  ingress:
    enabled: false
