apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.default.acme.email=ordforande@linkopingsfallskarmsklubb.se"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--providers.kubernetesingress.allowemptyservices=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowemptyservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      web:
        exposedPort: 80
      websecure:
        exposedPort: 443
    persistence:
      enabled: true
