apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace}}-{{ .Release.Name }}-headers@kubernetescrd
spec:
  rules:
    - host: 
      http:
        paths:
          - path: "/skywinone"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080
