apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    {{- if .Values.host }}
    - host: {{ .Values.host }}
    {{- else }}
    - host:
    {{- end }}
      http:
        paths:
          - path: "/skywinone"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080
