{{- if .Values.proxy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalHost }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app:  {{ .Release.Name }}
{{- end }}
