{{- if not .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: argocd-{{ .Release.Name }}@kubernetescrd
    {{- if .Values.host }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
    {{- end }}
spec:
  rules:
    {{- if .Values.host }}
    - host: {{ .Values.host }}
    {{- else }}
    - host:
    {{- end }}
      http:
        paths:
          - path: "/argocd"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-argocd-server
                port:
                  number: 80
  {{- if .Values.host }}
  tls:
    - hosts:
      - {{ .Values.host }}
  {{- end }}
{{- end }}
