{{- if not .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /argocd
{{- end }}
