{{- if not .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
  namespace: ingress
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /argocd
{{- end }}
