apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - host: insidan.linkopingsfallskarmsklubb.se
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 3000
  tls:
    - hosts:
      - insidan.linkopingsfallskarmsklubb.se
